namespace Projet_Ruyaga
{
    partial class User
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(User));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.textBoxID = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuDataGridViewUser = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuTextBoxRecherche = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButtonNettoyage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuTextBoxLogin = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButtonNouveau = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonSup = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonMod = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuTextBoxPrénom = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxNom = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.bunifuGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewUser)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.bunifuGroupBox1.BorderRadius = 15;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuTextBoxPassword);
            this.bunifuGroupBox1.Controls.Add(this.label4);
            this.bunifuGroupBox1.Controls.Add(this.textBoxID);
            this.bunifuGroupBox1.Controls.Add(this.bunifuTextBoxRecherche);
            this.bunifuGroupBox1.Controls.Add(this.bunifuButtonNettoyage);
            this.bunifuGroupBox1.Controls.Add(this.bunifuTextBoxLogin);
            this.bunifuGroupBox1.Controls.Add(this.label3);
            this.bunifuGroupBox1.Controls.Add(this.bunifuButtonNouveau);
            this.bunifuGroupBox1.Controls.Add(this.bunifuButtonSup);
            this.bunifuGroupBox1.Controls.Add(this.bunifuButtonMod);
            this.bunifuGroupBox1.Controls.Add(this.bunifuTextBoxPrénom);
            this.bunifuGroupBox1.Controls.Add(this.bunifuTextBoxNom);
            this.bunifuGroupBox1.Controls.Add(this.label2);
            this.bunifuGroupBox1.Controls.Add(this.label1);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(34, 13);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(521, 251);
            this.bunifuGroupBox1.TabIndex = 7;
            this.bunifuGroupBox1.TabStop = false;
            // 
            // textBoxID
            // 
            this.textBoxID.Location = new System.Drawing.Point(278, 215);
            this.textBoxID.Name = "textBoxID";
            this.textBoxID.Size = new System.Drawing.Size(56, 23);
            this.textBoxID.TabIndex = 35;
            this.textBoxID.Visible = false;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Arial Rounded MT Bold", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(122, 77);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(43, 15);
            this.label3.TabIndex = 30;
            this.label3.Text = "Login";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial Rounded MT Bold", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(349, 11);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(58, 15);
            this.label2.TabIndex = 24;
            this.label2.Text = "Prénom";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(122, 11);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(40, 15);
            this.label1.TabIndex = 23;
            this.label1.Text = "Nom ";
            // 
            // bunifuDataGridViewUser
            // 
            this.bunifuDataGridViewUser.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewUser.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridViewUser.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuDataGridViewUser.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewUser.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDataGridViewUser.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.bunifuDataGridViewUser.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewUser.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewUser.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridViewUser.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewUser.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewUser.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewUser.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewUser.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewUser.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewUser.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridViewUser.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewUser.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridViewUser.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewUser.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewUser.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridViewUser.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewUser.CurrentTheme.Name = null;
            this.bunifuDataGridViewUser.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridViewUser.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewUser.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewUser.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewUser.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewUser.Cursor = System.Windows.Forms.Cursors.Hand;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewUser.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridViewUser.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewUser.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewUser.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridViewUser.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewUser.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewUser.Location = new System.Drawing.Point(59, 270);
            this.bunifuDataGridViewUser.Name = "bunifuDataGridViewUser";
            this.bunifuDataGridViewUser.ReadOnly = true;
            this.bunifuDataGridViewUser.RowHeadersVisible = false;
            this.bunifuDataGridViewUser.RowTemplate.Height = 40;
            this.bunifuDataGridViewUser.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewUser.Size = new System.Drawing.Size(464, 288);
            this.bunifuDataGridViewUser.TabIndex = 6;
            this.bunifuDataGridViewUser.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuDataGridViewUser.Click += new System.EventHandler(this.envent_Click_remplichageForm);
            // 
            // bunifuTextBoxRecherche
            // 
            this.bunifuTextBoxRecherche.AcceptsReturn = false;
            this.bunifuTextBoxRecherche.AcceptsTab = false;
            this.bunifuTextBoxRecherche.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuTextBoxRecherche.AnimationSpeed = 200;
            this.bunifuTextBoxRecherche.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxRecherche.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxRecherche.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxRecherche.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxRecherche.BackgroundImage")));
            this.bunifuTextBoxRecherche.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxRecherche.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxRecherche.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxRecherche.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxRecherche.BorderRadius = 35;
            this.bunifuTextBoxRecherche.BorderThickness = 1;
            this.bunifuTextBoxRecherche.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxRecherche.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxRecherche.DefaultFont = new System.Drawing.Font("Arial Rounded MT Bold", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBoxRecherche.DefaultText = "";
            this.bunifuTextBoxRecherche.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxRecherche.HideSelection = true;
            this.bunifuTextBoxRecherche.IconLeft = null;
            this.bunifuTextBoxRecherche.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxRecherche.IconPadding = 5;
            this.bunifuTextBoxRecherche.IconRight = global::Projet_Ruyaga.Properties.Resources.outil_de_recherche;
            this.bunifuTextBoxRecherche.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxRecherche.Lines = new string[0];
            this.bunifuTextBoxRecherche.Location = new System.Drawing.Point(20, 203);
            this.bunifuTextBoxRecherche.MaxLength = 32767;
            this.bunifuTextBoxRecherche.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxRecherche.Modified = false;
            this.bunifuTextBoxRecherche.Multiline = false;
            this.bunifuTextBoxRecherche.Name = "bunifuTextBoxRecherche";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxRecherche.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxRecherche.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxRecherche.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxRecherche.OnIdleState = stateProperties8;
            this.bunifuTextBoxRecherche.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxRecherche.PasswordChar = '\0';
            this.bunifuTextBoxRecherche.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxRecherche.PlaceholderText = "Recherche...";
            this.bunifuTextBoxRecherche.ReadOnly = false;
            this.bunifuTextBoxRecherche.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxRecherche.SelectedText = "";
            this.bunifuTextBoxRecherche.SelectionLength = 0;
            this.bunifuTextBoxRecherche.SelectionStart = 0;
            this.bunifuTextBoxRecherche.ShortcutsEnabled = true;
            this.bunifuTextBoxRecherche.Size = new System.Drawing.Size(216, 38);
            this.bunifuTextBoxRecherche.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxRecherche.TabIndex = 34;
            this.bunifuTextBoxRecherche.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxRecherche.TextMarginBottom = 0;
            this.bunifuTextBoxRecherche.TextMarginLeft = 3;
            this.bunifuTextBoxRecherche.TextMarginTop = 0;
            this.bunifuTextBoxRecherche.TextPlaceholder = "Recherche...";
            this.bunifuTextBoxRecherche.UseSystemPasswordChar = false;
            this.bunifuTextBoxRecherche.WordWrap = true;
            this.bunifuTextBoxRecherche.TextChange += new System.EventHandler(this.Evenement_TextChange_DeRecherche);
            // 
            // bunifuButtonNettoyage
            // 
            this.bunifuButtonNettoyage.AllowAnimations = true;
            this.bunifuButtonNettoyage.AllowMouseEffects = true;
            this.bunifuButtonNettoyage.AllowToggling = false;
            this.bunifuButtonNettoyage.AnimationSpeed = 200;
            this.bunifuButtonNettoyage.AutoGenerateColors = false;
            this.bunifuButtonNettoyage.AutoRoundBorders = false;
            this.bunifuButtonNettoyage.AutoSizeLeftIcon = true;
            this.bunifuButtonNettoyage.AutoSizeRightIcon = true;
            this.bunifuButtonNettoyage.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonNettoyage.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNettoyage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonNettoyage.BackgroundImage")));
            this.bunifuButtonNettoyage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNettoyage.ButtonText = "Actualiser";
            this.bunifuButtonNettoyage.ButtonTextMarginLeft = 0;
            this.bunifuButtonNettoyage.ColorContrastOnClick = 45;
            this.bunifuButtonNettoyage.ColorContrastOnHover = 45;
            this.bunifuButtonNettoyage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonNettoyage.CustomizableEdges = borderEdges1;
            this.bunifuButtonNettoyage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonNettoyage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonNettoyage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonNettoyage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonNettoyage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonNettoyage.Font = new System.Drawing.Font("Century Schoolbook", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonNettoyage.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNettoyage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonNettoyage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonNettoyage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonNettoyage.IconMarginLeft = 11;
            this.bunifuButtonNettoyage.IconPadding = 10;
            this.bunifuButtonNettoyage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonNettoyage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonNettoyage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonNettoyage.IconSize = 25;
            this.bunifuButtonNettoyage.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNettoyage.IdleBorderRadius = 35;
            this.bunifuButtonNettoyage.IdleBorderThickness = 1;
            this.bunifuButtonNettoyage.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNettoyage.IdleIconLeftImage = global::Projet_Ruyaga.Properties.Resources.refresh_buttons;
            this.bunifuButtonNettoyage.IdleIconRightImage = null;
            this.bunifuButtonNettoyage.IndicateFocus = false;
            this.bunifuButtonNettoyage.Location = new System.Drawing.Point(370, 199);
            this.bunifuButtonNettoyage.Name = "bunifuButtonNettoyage";
            this.bunifuButtonNettoyage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonNettoyage.OnDisabledState.BorderRadius = 35;
            this.bunifuButtonNettoyage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNettoyage.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonNettoyage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonNettoyage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonNettoyage.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonNettoyage.OnDisabledState.IconRightImage = null;
            this.bunifuButtonNettoyage.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonNettoyage.onHoverState.BorderRadius = 35;
            this.bunifuButtonNettoyage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNettoyage.onHoverState.BorderThickness = 1;
            this.bunifuButtonNettoyage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonNettoyage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNettoyage.onHoverState.IconLeftImage = null;
            this.bunifuButtonNettoyage.onHoverState.IconRightImage = null;
            this.bunifuButtonNettoyage.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNettoyage.OnIdleState.BorderRadius = 35;
            this.bunifuButtonNettoyage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNettoyage.OnIdleState.BorderThickness = 1;
            this.bunifuButtonNettoyage.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNettoyage.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNettoyage.OnIdleState.IconLeftImage = global::Projet_Ruyaga.Properties.Resources.refresh_buttons;
            this.bunifuButtonNettoyage.OnIdleState.IconRightImage = null;
            this.bunifuButtonNettoyage.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonNettoyage.OnPressedState.BorderRadius = 35;
            this.bunifuButtonNettoyage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNettoyage.OnPressedState.BorderThickness = 1;
            this.bunifuButtonNettoyage.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonNettoyage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNettoyage.OnPressedState.IconLeftImage = null;
            this.bunifuButtonNettoyage.OnPressedState.IconRightImage = null;
            this.bunifuButtonNettoyage.Size = new System.Drawing.Size(130, 39);
            this.bunifuButtonNettoyage.TabIndex = 33;
            this.bunifuButtonNettoyage.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonNettoyage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonNettoyage.TextMarginLeft = 0;
            this.bunifuButtonNettoyage.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonNettoyage.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonNettoyage.Click += new System.EventHandler(this.bunifuButtonNettoyage_Click);
            // 
            // bunifuTextBoxLogin
            // 
            this.bunifuTextBoxLogin.AcceptsReturn = false;
            this.bunifuTextBoxLogin.AcceptsTab = false;
            this.bunifuTextBoxLogin.AnimationSpeed = 200;
            this.bunifuTextBoxLogin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxLogin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxLogin.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxLogin.BackgroundImage")));
            this.bunifuTextBoxLogin.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxLogin.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxLogin.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxLogin.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxLogin.BorderRadius = 15;
            this.bunifuTextBoxLogin.BorderThickness = 1;
            this.bunifuTextBoxLogin.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxLogin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxLogin.DefaultFont = new System.Drawing.Font("Arial Rounded MT Bold", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBoxLogin.DefaultText = "";
            this.bunifuTextBoxLogin.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxLogin.HideSelection = true;
            this.bunifuTextBoxLogin.IconLeft = null;
            this.bunifuTextBoxLogin.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxLogin.IconPadding = 10;
            this.bunifuTextBoxLogin.IconRight = null;
            this.bunifuTextBoxLogin.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxLogin.Lines = new string[0];
            this.bunifuTextBoxLogin.Location = new System.Drawing.Point(39, 95);
            this.bunifuTextBoxLogin.MaxLength = 32767;
            this.bunifuTextBoxLogin.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxLogin.Modified = false;
            this.bunifuTextBoxLogin.Multiline = false;
            this.bunifuTextBoxLogin.Name = "bunifuTextBoxLogin";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxLogin.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxLogin.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxLogin.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxLogin.OnIdleState = stateProperties12;
            this.bunifuTextBoxLogin.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxLogin.PasswordChar = '\0';
            this.bunifuTextBoxLogin.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxLogin.PlaceholderText = "Login";
            this.bunifuTextBoxLogin.ReadOnly = false;
            this.bunifuTextBoxLogin.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxLogin.SelectedText = "";
            this.bunifuTextBoxLogin.SelectionLength = 0;
            this.bunifuTextBoxLogin.SelectionStart = 0;
            this.bunifuTextBoxLogin.ShortcutsEnabled = true;
            this.bunifuTextBoxLogin.Size = new System.Drawing.Size(208, 38);
            this.bunifuTextBoxLogin.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxLogin.TabIndex = 31;
            this.bunifuTextBoxLogin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxLogin.TextMarginBottom = 0;
            this.bunifuTextBoxLogin.TextMarginLeft = 3;
            this.bunifuTextBoxLogin.TextMarginTop = 0;
            this.bunifuTextBoxLogin.TextPlaceholder = "Login";
            this.bunifuTextBoxLogin.UseSystemPasswordChar = false;
            this.bunifuTextBoxLogin.WordWrap = true;
            // 
            // bunifuButtonNouveau
            // 
            this.bunifuButtonNouveau.AllowAnimations = true;
            this.bunifuButtonNouveau.AllowMouseEffects = true;
            this.bunifuButtonNouveau.AllowToggling = false;
            this.bunifuButtonNouveau.AnimationSpeed = 200;
            this.bunifuButtonNouveau.AutoGenerateColors = false;
            this.bunifuButtonNouveau.AutoRoundBorders = false;
            this.bunifuButtonNouveau.AutoSizeLeftIcon = true;
            this.bunifuButtonNouveau.AutoSizeRightIcon = true;
            this.bunifuButtonNouveau.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonNouveau.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNouveau.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonNouveau.BackgroundImage")));
            this.bunifuButtonNouveau.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNouveau.ButtonText = "Ajouter";
            this.bunifuButtonNouveau.ButtonTextMarginLeft = 0;
            this.bunifuButtonNouveau.ColorContrastOnClick = 45;
            this.bunifuButtonNouveau.ColorContrastOnHover = 45;
            this.bunifuButtonNouveau.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonNouveau.CustomizableEdges = borderEdges2;
            this.bunifuButtonNouveau.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonNouveau.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonNouveau.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonNouveau.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonNouveau.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonNouveau.Font = new System.Drawing.Font("Century Schoolbook", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonNouveau.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNouveau.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonNouveau.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonNouveau.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonNouveau.IconMarginLeft = 11;
            this.bunifuButtonNouveau.IconPadding = 5;
            this.bunifuButtonNouveau.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonNouveau.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonNouveau.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonNouveau.IconSize = 25;
            this.bunifuButtonNouveau.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNouveau.IdleBorderRadius = 20;
            this.bunifuButtonNouveau.IdleBorderThickness = 1;
            this.bunifuButtonNouveau.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNouveau.IdleIconLeftImage = global::Projet_Ruyaga.Properties.Resources.buy;
            this.bunifuButtonNouveau.IdleIconRightImage = null;
            this.bunifuButtonNouveau.IndicateFocus = false;
            this.bunifuButtonNouveau.Location = new System.Drawing.Point(12, 144);
            this.bunifuButtonNouveau.Name = "bunifuButtonNouveau";
            this.bunifuButtonNouveau.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonNouveau.OnDisabledState.BorderRadius = 20;
            this.bunifuButtonNouveau.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNouveau.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonNouveau.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonNouveau.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonNouveau.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonNouveau.OnDisabledState.IconRightImage = null;
            this.bunifuButtonNouveau.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonNouveau.onHoverState.BorderRadius = 20;
            this.bunifuButtonNouveau.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNouveau.onHoverState.BorderThickness = 1;
            this.bunifuButtonNouveau.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonNouveau.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNouveau.onHoverState.IconLeftImage = null;
            this.bunifuButtonNouveau.onHoverState.IconRightImage = null;
            this.bunifuButtonNouveau.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNouveau.OnIdleState.BorderRadius = 20;
            this.bunifuButtonNouveau.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNouveau.OnIdleState.BorderThickness = 1;
            this.bunifuButtonNouveau.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonNouveau.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNouveau.OnIdleState.IconLeftImage = global::Projet_Ruyaga.Properties.Resources.buy;
            this.bunifuButtonNouveau.OnIdleState.IconRightImage = null;
            this.bunifuButtonNouveau.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonNouveau.OnPressedState.BorderRadius = 20;
            this.bunifuButtonNouveau.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonNouveau.OnPressedState.BorderThickness = 1;
            this.bunifuButtonNouveau.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonNouveau.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonNouveau.OnPressedState.IconLeftImage = null;
            this.bunifuButtonNouveau.OnPressedState.IconRightImage = null;
            this.bunifuButtonNouveau.Size = new System.Drawing.Size(150, 39);
            this.bunifuButtonNouveau.TabIndex = 27;
            this.bunifuButtonNouveau.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonNouveau.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonNouveau.TextMarginLeft = 0;
            this.bunifuButtonNouveau.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonNouveau.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonNouveau.Click += new System.EventHandler(this.bunifuButtonNouveau_Click);
            // 
            // bunifuButtonSup
            // 
            this.bunifuButtonSup.AllowAnimations = true;
            this.bunifuButtonSup.AllowMouseEffects = true;
            this.bunifuButtonSup.AllowToggling = false;
            this.bunifuButtonSup.AnimationSpeed = 200;
            this.bunifuButtonSup.AutoGenerateColors = false;
            this.bunifuButtonSup.AutoRoundBorders = false;
            this.bunifuButtonSup.AutoSizeLeftIcon = true;
            this.bunifuButtonSup.AutoSizeRightIcon = true;
            this.bunifuButtonSup.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonSup.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonSup.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonSup.BackgroundImage")));
            this.bunifuButtonSup.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonSup.ButtonText = "Supprimer";
            this.bunifuButtonSup.ButtonTextMarginLeft = 0;
            this.bunifuButtonSup.ColorContrastOnClick = 45;
            this.bunifuButtonSup.ColorContrastOnHover = 45;
            this.bunifuButtonSup.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonSup.CustomizableEdges = borderEdges3;
            this.bunifuButtonSup.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonSup.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonSup.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonSup.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonSup.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonSup.Font = new System.Drawing.Font("Century Schoolbook", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonSup.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSup.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonSup.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonSup.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonSup.IconMarginLeft = 11;
            this.bunifuButtonSup.IconPadding = 5;
            this.bunifuButtonSup.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonSup.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonSup.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonSup.IconSize = 25;
            this.bunifuButtonSup.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonSup.IdleBorderRadius = 20;
            this.bunifuButtonSup.IdleBorderThickness = 1;
            this.bunifuButtonSup.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonSup.IdleIconLeftImage = global::Projet_Ruyaga.Properties.Resources.sup;
            this.bunifuButtonSup.IdleIconRightImage = null;
            this.bunifuButtonSup.IndicateFocus = false;
            this.bunifuButtonSup.Location = new System.Drawing.Point(355, 144);
            this.bunifuButtonSup.Name = "bunifuButtonSup";
            this.bunifuButtonSup.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonSup.OnDisabledState.BorderRadius = 20;
            this.bunifuButtonSup.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonSup.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonSup.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonSup.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonSup.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonSup.OnDisabledState.IconRightImage = null;
            this.bunifuButtonSup.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonSup.onHoverState.BorderRadius = 20;
            this.bunifuButtonSup.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonSup.onHoverState.BorderThickness = 1;
            this.bunifuButtonSup.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonSup.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSup.onHoverState.IconLeftImage = null;
            this.bunifuButtonSup.onHoverState.IconRightImage = null;
            this.bunifuButtonSup.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonSup.OnIdleState.BorderRadius = 20;
            this.bunifuButtonSup.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonSup.OnIdleState.BorderThickness = 1;
            this.bunifuButtonSup.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonSup.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSup.OnIdleState.IconLeftImage = global::Projet_Ruyaga.Properties.Resources.sup;
            this.bunifuButtonSup.OnIdleState.IconRightImage = null;
            this.bunifuButtonSup.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonSup.OnPressedState.BorderRadius = 20;
            this.bunifuButtonSup.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonSup.OnPressedState.BorderThickness = 1;
            this.bunifuButtonSup.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonSup.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonSup.OnPressedState.IconLeftImage = null;
            this.bunifuButtonSup.OnPressedState.IconRightImage = null;
            this.bunifuButtonSup.Size = new System.Drawing.Size(150, 39);
            this.bunifuButtonSup.TabIndex = 29;
            this.bunifuButtonSup.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonSup.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonSup.TextMarginLeft = 0;
            this.bunifuButtonSup.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonSup.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonSup.Click += new System.EventHandler(this.bunifuButtonSup_Click);
            // 
            // bunifuButtonMod
            // 
            this.bunifuButtonMod.AllowAnimations = true;
            this.bunifuButtonMod.AllowMouseEffects = true;
            this.bunifuButtonMod.AllowToggling = false;
            this.bunifuButtonMod.AnimationSpeed = 200;
            this.bunifuButtonMod.AutoGenerateColors = false;
            this.bunifuButtonMod.AutoRoundBorders = false;
            this.bunifuButtonMod.AutoSizeLeftIcon = true;
            this.bunifuButtonMod.AutoSizeRightIcon = true;
            this.bunifuButtonMod.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMod.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonMod.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMod.BackgroundImage")));
            this.bunifuButtonMod.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMod.ButtonText = "Modifier";
            this.bunifuButtonMod.ButtonTextMarginLeft = 0;
            this.bunifuButtonMod.ColorContrastOnClick = 45;
            this.bunifuButtonMod.ColorContrastOnHover = 45;
            this.bunifuButtonMod.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButtonMod.CustomizableEdges = borderEdges4;
            this.bunifuButtonMod.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMod.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMod.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMod.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMod.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMod.Font = new System.Drawing.Font("Century Schoolbook", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMod.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMod.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMod.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMod.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMod.IconMarginLeft = 11;
            this.bunifuButtonMod.IconPadding = 5;
            this.bunifuButtonMod.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMod.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMod.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMod.IconSize = 25;
            this.bunifuButtonMod.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonMod.IdleBorderRadius = 20;
            this.bunifuButtonMod.IdleBorderThickness = 1;
            this.bunifuButtonMod.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonMod.IdleIconLeftImage = global::Projet_Ruyaga.Properties.Resources.modi;
            this.bunifuButtonMod.IdleIconRightImage = null;
            this.bunifuButtonMod.IndicateFocus = false;
            this.bunifuButtonMod.Location = new System.Drawing.Point(182, 144);
            this.bunifuButtonMod.Name = "bunifuButtonMod";
            this.bunifuButtonMod.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMod.OnDisabledState.BorderRadius = 20;
            this.bunifuButtonMod.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMod.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMod.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMod.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMod.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMod.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMod.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMod.onHoverState.BorderRadius = 20;
            this.bunifuButtonMod.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMod.onHoverState.BorderThickness = 1;
            this.bunifuButtonMod.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMod.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMod.onHoverState.IconLeftImage = null;
            this.bunifuButtonMod.onHoverState.IconRightImage = null;
            this.bunifuButtonMod.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonMod.OnIdleState.BorderRadius = 20;
            this.bunifuButtonMod.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMod.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMod.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonMod.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMod.OnIdleState.IconLeftImage = global::Projet_Ruyaga.Properties.Resources.modi;
            this.bunifuButtonMod.OnIdleState.IconRightImage = null;
            this.bunifuButtonMod.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMod.OnPressedState.BorderRadius = 20;
            this.bunifuButtonMod.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMod.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMod.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMod.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMod.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMod.OnPressedState.IconRightImage = null;
            this.bunifuButtonMod.Size = new System.Drawing.Size(150, 39);
            this.bunifuButtonMod.TabIndex = 28;
            this.bunifuButtonMod.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMod.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMod.TextMarginLeft = 0;
            this.bunifuButtonMod.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMod.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonMod.Click += new System.EventHandler(this.bunifuButtonMod_Click);
            // 
            // bunifuTextBoxPrénom
            // 
            this.bunifuTextBoxPrénom.AcceptsReturn = false;
            this.bunifuTextBoxPrénom.AcceptsTab = false;
            this.bunifuTextBoxPrénom.AnimationSpeed = 200;
            this.bunifuTextBoxPrénom.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPrénom.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPrénom.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxPrénom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPrénom.BackgroundImage")));
            this.bunifuTextBoxPrénom.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPrénom.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPrénom.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPrénom.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPrénom.BorderRadius = 15;
            this.bunifuTextBoxPrénom.BorderThickness = 1;
            this.bunifuTextBoxPrénom.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPrénom.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPrénom.DefaultFont = new System.Drawing.Font("Arial Rounded MT Bold", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBoxPrénom.DefaultText = "";
            this.bunifuTextBoxPrénom.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPrénom.HideSelection = true;
            this.bunifuTextBoxPrénom.IconLeft = null;
            this.bunifuTextBoxPrénom.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPrénom.IconPadding = 10;
            this.bunifuTextBoxPrénom.IconRight = null;
            this.bunifuTextBoxPrénom.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPrénom.Lines = new string[0];
            this.bunifuTextBoxPrénom.Location = new System.Drawing.Point(278, 30);
            this.bunifuTextBoxPrénom.MaxLength = 32767;
            this.bunifuTextBoxPrénom.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPrénom.Modified = false;
            this.bunifuTextBoxPrénom.Multiline = false;
            this.bunifuTextBoxPrénom.Name = "bunifuTextBoxPrénom";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPrénom.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPrénom.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPrénom.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPrénom.OnIdleState = stateProperties16;
            this.bunifuTextBoxPrénom.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxPrénom.PasswordChar = '\0';
            this.bunifuTextBoxPrénom.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxPrénom.PlaceholderText = "Entrer son Prenom";
            this.bunifuTextBoxPrénom.ReadOnly = false;
            this.bunifuTextBoxPrénom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPrénom.SelectedText = "";
            this.bunifuTextBoxPrénom.SelectionLength = 0;
            this.bunifuTextBoxPrénom.SelectionStart = 0;
            this.bunifuTextBoxPrénom.ShortcutsEnabled = true;
            this.bunifuTextBoxPrénom.Size = new System.Drawing.Size(207, 38);
            this.bunifuTextBoxPrénom.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxPrénom.TabIndex = 26;
            this.bunifuTextBoxPrénom.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxPrénom.TextMarginBottom = 0;
            this.bunifuTextBoxPrénom.TextMarginLeft = 3;
            this.bunifuTextBoxPrénom.TextMarginTop = 0;
            this.bunifuTextBoxPrénom.TextPlaceholder = "Entrer son Prenom";
            this.bunifuTextBoxPrénom.UseSystemPasswordChar = false;
            this.bunifuTextBoxPrénom.WordWrap = true;
            // 
            // bunifuTextBoxNom
            // 
            this.bunifuTextBoxNom.AcceptsReturn = false;
            this.bunifuTextBoxNom.AcceptsTab = false;
            this.bunifuTextBoxNom.AnimationSpeed = 200;
            this.bunifuTextBoxNom.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxNom.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxNom.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxNom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxNom.BackgroundImage")));
            this.bunifuTextBoxNom.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxNom.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxNom.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxNom.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxNom.BorderRadius = 15;
            this.bunifuTextBoxNom.BorderThickness = 1;
            this.bunifuTextBoxNom.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxNom.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxNom.DefaultFont = new System.Drawing.Font("Arial Rounded MT Bold", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBoxNom.DefaultText = "";
            this.bunifuTextBoxNom.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxNom.HideSelection = true;
            this.bunifuTextBoxNom.IconLeft = null;
            this.bunifuTextBoxNom.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxNom.IconPadding = 10;
            this.bunifuTextBoxNom.IconRight = null;
            this.bunifuTextBoxNom.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxNom.Lines = new string[0];
            this.bunifuTextBoxNom.Location = new System.Drawing.Point(39, 30);
            this.bunifuTextBoxNom.MaxLength = 32767;
            this.bunifuTextBoxNom.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxNom.Modified = false;
            this.bunifuTextBoxNom.Multiline = false;
            this.bunifuTextBoxNom.Name = "bunifuTextBoxNom";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxNom.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxNom.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxNom.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxNom.OnIdleState = stateProperties20;
            this.bunifuTextBoxNom.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxNom.PasswordChar = '\0';
            this.bunifuTextBoxNom.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxNom.PlaceholderText = "Entrer le nom";
            this.bunifuTextBoxNom.ReadOnly = false;
            this.bunifuTextBoxNom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxNom.SelectedText = "";
            this.bunifuTextBoxNom.SelectionLength = 0;
            this.bunifuTextBoxNom.SelectionStart = 0;
            this.bunifuTextBoxNom.ShortcutsEnabled = true;
            this.bunifuTextBoxNom.Size = new System.Drawing.Size(208, 38);
            this.bunifuTextBoxNom.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxNom.TabIndex = 25;
            this.bunifuTextBoxNom.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxNom.TextMarginBottom = 0;
            this.bunifuTextBoxNom.TextMarginLeft = 3;
            this.bunifuTextBoxNom.TextMarginTop = 0;
            this.bunifuTextBoxNom.TextPlaceholder = "Entrer le nom";
            this.bunifuTextBoxNom.UseSystemPasswordChar = false;
            this.bunifuTextBoxNom.WordWrap = true;
            // 
            // bunifuTextBoxPassword
            // 
            this.bunifuTextBoxPassword.AcceptsReturn = false;
            this.bunifuTextBoxPassword.AcceptsTab = false;
            this.bunifuTextBoxPassword.AnimationSpeed = 200;
            this.bunifuTextBoxPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPassword.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPassword.BackgroundImage")));
            this.bunifuTextBoxPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPassword.BorderRadius = 15;
            this.bunifuTextBoxPassword.BorderThickness = 1;
            this.bunifuTextBoxPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.DefaultFont = new System.Drawing.Font("Arial Rounded MT Bold", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBoxPassword.DefaultText = "";
            this.bunifuTextBoxPassword.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPassword.HideSelection = true;
            this.bunifuTextBoxPassword.IconLeft = null;
            this.bunifuTextBoxPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.IconPadding = 10;
            this.bunifuTextBoxPassword.IconRight = null;
            this.bunifuTextBoxPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.Lines = new string[0];
            this.bunifuTextBoxPassword.Location = new System.Drawing.Point(278, 95);
            this.bunifuTextBoxPassword.MaxLength = 32767;
            this.bunifuTextBoxPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPassword.Modified = false;
            this.bunifuTextBoxPassword.Multiline = false;
            this.bunifuTextBoxPassword.Name = "bunifuTextBoxPassword";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnIdleState = stateProperties4;
            this.bunifuTextBoxPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxPassword.PasswordChar = '\0';
            this.bunifuTextBoxPassword.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxPassword.PlaceholderText = "**************";
            this.bunifuTextBoxPassword.ReadOnly = false;
            this.bunifuTextBoxPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPassword.SelectedText = "";
            this.bunifuTextBoxPassword.SelectionLength = 0;
            this.bunifuTextBoxPassword.SelectionStart = 0;
            this.bunifuTextBoxPassword.ShortcutsEnabled = true;
            this.bunifuTextBoxPassword.Size = new System.Drawing.Size(208, 38);
            this.bunifuTextBoxPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxPassword.TabIndex = 37;
            this.bunifuTextBoxPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuTextBoxPassword.TextMarginBottom = 0;
            this.bunifuTextBoxPassword.TextMarginLeft = 3;
            this.bunifuTextBoxPassword.TextMarginTop = 0;
            this.bunifuTextBoxPassword.TextPlaceholder = "**************";
            this.bunifuTextBoxPassword.UseSystemPasswordChar = false;
            this.bunifuTextBoxPassword.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Arial Rounded MT Bold", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(343, 77);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(92, 15);
            this.label4.TabIndex = 36;
            this.label4.Text = "Mot de Passe";
            // 
            // User
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(589, 570);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.bunifuDataGridViewUser);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "User";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "User";
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewUser)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.TextBox textBoxID;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxRecherche;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonNettoyage;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxLogin;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonNouveau;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonSup;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMod;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPrénom;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxNom;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewUser;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPassword;
        private System.Windows.Forms.Label label4;
    }
}